config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :entities, only: [:new, :create]

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
# == Schema Information
#
# Table name: conditions
#
#  id           :integer          not null, primary key
#  term         :integer          default("0")
#  period       :integer          default("0")
#  rate         :integer          default("0")
#  overdue_rate :integer          default("0")
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Condition < ApplicationRecord
  has_many :investments, inverse_of: :condition

  def self.default
    first
  end

  def decorate
    ConditionDecorator.new(self)
  end
end

app/models/entity.rb
# == Schema Information
#
# Table name: entities
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Entity < ApplicationRecord
  has_one :investment, inverse_of: :entity, dependent: :destroy
end

app/models/investment.rb
# == Schema Information
#
# Table name: investments
#
#  id           :integer          not null, primary key
#  term         :integer          default("0")
#  period       :integer          default("0")
#  rate         :integer          default("0")
#  overdue_rate :integer          default("0")
#  sum          :float            default("0.0")
#  loan_paid    :float            default("0.0")
#  entity_id    :integer          not null
#  condition_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_investments_on_condition_id  (condition_id)
#  index_investments_on_entity_id     (entity_id)
#

class Investment < ApplicationRecord
  belongs_to :entity, inverse_of: :investment
  belongs_to :condition, inverse_of: :investments

  has_many :periods, inverse_of: :investment, dependent: :destroy
end

app/models/period.rb
# == Schema Information
#
# Table name: periods
#
#  id            :integer          not null, primary key
#  status        :string           not null
#  investment_id :integer          not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_periods_on_investment_id  (investment_id)
#

class Period < ApplicationRecord
  STATUSES = %w(in_time delay premature).freeze

  belongs_to :investment, inverse_of: :periods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def new
    @form = EntityFormBuilder.new.build
  end

  def create
    service = EntityService.new(params)
    if service.save
      redirect_to root_path
    else
      @form = service.form
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @view = IndexObject.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/_form.html.slim
= form_tag("/entities", method: "post", class: "form-horizontal")
  - if @form.errors.present?
    - @form.errors.each do |field, msg|
        p
        = t "fields.#{field}"
        | :&nbsp;
        = msg.join(', ')

  div.form-group
    label Название
    = text_field(:entity, :name, value: @form.name, class: 'form-control')
  div.form-group
    label Сумма
    = number_field(:entity, :sum, value: @form.sum, class: 'form-control')

  - @form.statuses.each_with_index do |status, index|
    div.form-group
      label= "#{index + 1} месяц"
      = select_tag('entity[statuses][]', options_for_select(@form.statuses_normalized), class: 'form-control')

  div.form-group
    = submit_tag('Добавить', class: 'btn btn-success')

app/views/entities/new.html.slim
.col-md-12
  .row
    = render 'form'

app/views/home/index.html.slim
.col-md-12
  .row
    = react_component('Calculator', { realisticProfitability: @view.realisitic_profitability, optimisticProfitability: @view.optimistic_profitability })

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectFlow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title ProjectFlow
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = render 'shared/navigation'
    .container
      = yield

app/views/shared/_navigation.html.slim
nav.navbar.navbar-default
  .container-fluid
    ul.nav.navbar-nav
      li
        = link_to 'Калькулятор', root_path
      li
        = link_to 'Добавить ЮЛ', new_entity_path